services: 
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: vaibhav
      MYSQL_DATABASE: crudapp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb/init.sql
    
  flask:
    build:
      context: .
    ports:
      - "21221:21221"
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: vaibhav
      MYSQL_DATABASE: crudapp
    depends_on:
      - db
volumes:
  db_data: